//
//  Copyright (c) 2020 Rally Tactical Systems, Inc.
//  All rights reserved.
//

#ifndef EngagePlatformNotifications_h
#define EngagePlatformNotifications_h

#define ENGAGE_PLATFORM_CHANGE_APP_ACTIVATED                        "ENGAGE_PLATFORM_CHANGE_APP_ACTIVATED"
#define ENGAGE_PLATFORM_CHANGE_APP_DEACTIVATED                      "ENGAGE_PLATFORM_CHANGE_APP_DEACTIVATED"
#define ENGAGE_PLATFORM_CHANGE_APP_TERMINATING                      "ENGAGE_PLATFORM_CHANGE_APP_TERMINATING"
#define ENGAGE_PLATFORM_CHANGE_APP_PAUSING                          "ENGAGE_PLATFORM_CHANGE_APP_PAUSING"
#define ENGAGE_PLATFORM_CHANGE_APP_PAUSED                           "ENGAGE_PLATFORM_CHANGE_APP_PAUSED"
#define ENGAGE_PLATFORM_CHANGE_APP_RESUMING                         "ENGAGE_PLATFORM_CHANGE_APP_RESUMING"
#define ENGAGE_PLATFORM_CHANGE_APP_RESUMED                          "ENGAGE_PLATFORM_CHANGE_APP_RESUMED"
#define ENGAGE_PLATFORM_CHANGE_APP_LOW_MEMORY_STATE_ON              "ENGAGE_PLATFORM_CHANGE_APP_LOW_MEMORY_STATE_ON"
#define ENGAGE_PLATFORM_CHANGE_APP_LOW_MEMORY_STATE_OFF             "ENGAGE_PLATFORM_CHANGE_APP_LOW_MEMORY_STATE_OFF"
#define ENGAGE_PLATFORM_CHANGE_APP_LOW_POWER_STATE_ON               "ENGAGE_PLATFORM_CHANGE_APP_LOW_POWER_STATE_ON"
#define ENGAGE_PLATFORM_CHANGE_APP_LOW_POWER_STATE_OFF              "ENGAGE_PLATFORM_CHANGE_APP_LOW_POWER_STATE_OFF"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_STATE_ON                 "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_STATE_ON"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_STATE_OFF                "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_STATE_OFF"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_LOW_BANDWIDTH_ON         "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_LOW_BANDWIDTH_ON"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_LOW_BANDWIDTH_OFF        "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_LOW_BANDWIDTH_OFF"
#define ENGAGE_PLATFORM_CHANGE_APP_ENTERED_BACKGROUND_MODE          "ENGAGE_PLATFORM_CHANGE_APP_ENTERED_BACKGROUND_MODE"
#define ENGAGE_PLATFORM_CHANGE_APP_LEFT_BACKGROUND_MODE             "ENGAGE_PLATFORM_CHANGE_APP_LEFT_BACKGROUND_MODE"
#define ENGAGE_PLATFORM_CHANGE_APP_AUDIO_SYSTEM_OFFLINE             "ENGAGE_PLATFORM_CHANGE_APP_AUDIO_SYSTEM_OFFLINE"
#define ENGAGE_PLATFORM_CHANGE_APP_AUDIO_SYSTEM_ONLINE              "ENGAGE_PLATFORM_CHANGE_APP_AUDIO_SYSTEM_ONLINE"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_SYSTEM_OFFLINE           "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_SYSTEM_OFFLINE"
#define ENGAGE_PLATFORM_CHANGE_APP_NETWORK_SYSTEM_ONLINE            "ENGAGE_PLATFORM_CHANGE_APP_NETWORK_SYSTEM_ONLINE"

#endif // EngagePlatformNotifications_h
