#!/bin/bash

# To run in test mode for a random number of seconds with constant restart
# set NSM_RUN_SECS to a positive number

while [ true ]
do
    if [[ "${NSM_RUN_SECS}" == "" ]]; then
        /etc/nsm//onIdle.sh ''
        python3 /etc/nsm/_nsm.py ${1} ${2} ${3} ${4} ${5} ${6}
        /etc/nsm//onIdle.sh ''
        break
    else
        /etc/nsm//onIdle.sh ''
        python3 /etc/nsm/_nsm.py --max-run-secs $(( ($RANDOM % ${NSM_RUN_SECS}) + ${NSM_RUN_SECS} )) ${1} ${2} ${3} ${4} ${5} ${6}
        /etc/nsm//onIdle.sh ''
        sleep ${NSM_RUN_SECS}
    fi
done
